### ISSUE TITLE
yt3.ggpht.com

### ISSUE THREAD

**Issue by p1r473** [mayesidevel/PiHoleLists#1]
This is a valid google API that seems to service YouTube music
I believe this is a non malicious false positive
With the domain blocked:
![image](https://user-images.githubusercontent.com/9235633/156211878-2e816c04-a095-46d8-bddc-035569dd5a75.png)
Unblocked:
![image](https://user-images.githubusercontent.com/9235633/156211912-08eb00f0-4855-474d-a8e4-e1c3160a38aa.png)

@mayesidevel

**Comment by mayesidev** [comment]
Good catch, thanks! This domain was also already in the Whitelist file, so it wasn't really being blocked on my network anyway. Removed it from the list under commit- https://github.com/mayesidevel/PiHoleLists/commit/d68d2750f6fa5f6177dceed540eaa9140234afd4.
